// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/v1/classification.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataClassification declares what kind of data a field is allowed to carry.
// It is declared once, on the field, and is the input to lint enforcement
// (scripts/check-proto-classification.py) and to the generated attribute
// manifest consumed by runtime validators.
type DataClassification int32

const (
	// Not declared. Fields carrying free-form text must not use this value.
	DataClassification_DATA_CLASSIFICATION_UNSPECIFIED DataClassification = 0
	// Bounded, non-tenant-identifying values: enum-like strings, model names,
	// provider names, surface names, units, status codes.
	DataClassification_DATA_CLASSIFICATION_SAFE DataClassification = 1
	// Values that identify a tenant, principal, or record: organization ids,
	// workspace ids, user ids, request ids, idempotency keys, cursors.
	DataClassification_DATA_CLASSIFICATION_IDENTIFIER DataClassification = 2
	// Filesystem paths, URLs, repository refs, and other location strings.
	DataClassification_DATA_CLASSIFICATION_PATH DataClassification = 3
	// Operator- or model-authored free text and binary payloads: message bodies,
	// corrections, tool output, attachment bytes.
	DataClassification_DATA_CLASSIFICATION_CONTENT DataClassification = 4
	// Secret material: tokens, keys, passwords, signed bearer values. Fields with
	// this classification must never be persisted or logged in cleartext.
	DataClassification_DATA_CLASSIFICATION_CREDENTIAL DataClassification = 5
)

// Enum value maps for DataClassification.
var (
	DataClassification_name = map[int32]string{
		0: "DATA_CLASSIFICATION_UNSPECIFIED",
		1: "DATA_CLASSIFICATION_SAFE",
		2: "DATA_CLASSIFICATION_IDENTIFIER",
		3: "DATA_CLASSIFICATION_PATH",
		4: "DATA_CLASSIFICATION_CONTENT",
		5: "DATA_CLASSIFICATION_CREDENTIAL",
	}
	DataClassification_value = map[string]int32{
		"DATA_CLASSIFICATION_UNSPECIFIED": 0,
		"DATA_CLASSIFICATION_SAFE":        1,
		"DATA_CLASSIFICATION_IDENTIFIER":  2,
		"DATA_CLASSIFICATION_PATH":        3,
		"DATA_CLASSIFICATION_CONTENT":     4,
		"DATA_CLASSIFICATION_CREDENTIAL":  5,
	}
)

func (x DataClassification) Enum() *DataClassification {
	p := new(DataClassification)
	*p = x
	return p
}

func (x DataClassification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataClassification) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_classification_proto_enumTypes[0].Descriptor()
}

func (DataClassification) Type() protoreflect.EnumType {
	return &file_common_v1_classification_proto_enumTypes[0]
}

func (x DataClassification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataClassification.Descriptor instead.
func (DataClassification) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_classification_proto_rawDescGZIP(), []int{0}
}

var file_common_v1_classification_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*DataClassification)(nil),
		Field:         51008,
		Name:          "common.v1.classification",
		Tag:           "varint,51008,opt,name=classification,enum=common.v1.DataClassification",
		Filename:      "common/v1/classification.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional common.v1.DataClassification classification = 51008;
	E_Classification = &file_common_v1_classification_proto_extTypes[0]
)

var File_common_v1_classification_proto protoreflect.FileDescriptor

const file_common_v1_classification_proto_rawDesc = "" +
	"\n" +
	"\x1ecommon/v1/classification.proto\x12\tcommon.v1\x1a google/protobuf/descriptor.proto*\xde\x01\n" +
	"\x12DataClassification\x12#\n" +
	"\x1fDATA_CLASSIFICATION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DATA_CLASSIFICATION_SAFE\x10\x01\x12\"\n" +
	"\x1eDATA_CLASSIFICATION_IDENTIFIER\x10\x02\x12\x1c\n" +
	"\x18DATA_CLASSIFICATION_PATH\x10\x03\x12\x1f\n" +
	"\x1bDATA_CLASSIFICATION_CONTENT\x10\x04\x12\"\n" +
	"\x1eDATA_CLASSIFICATION_CREDENTIAL\x10\x05:f\n" +
	"\x0eclassification\x12\x1d.google.protobuf.FieldOptions\x18\xc0\x8e\x03 \x01(\x0e2\x1d.common.v1.DataClassificationR\x0eclassificationB7Z5github.com/evalops/platform/gen/go/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_classification_proto_rawDescOnce sync.Once
	file_common_v1_classification_proto_rawDescData []byte
)

func file_common_v1_classification_proto_rawDescGZIP() []byte {
	file_common_v1_classification_proto_rawDescOnce.Do(func() {
		file_common_v1_classification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_classification_proto_rawDesc), len(file_common_v1_classification_proto_rawDesc)))
	})
	return file_common_v1_classification_proto_rawDescData
}

var file_common_v1_classification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_classification_proto_goTypes = []any{
	(DataClassification)(0),           // 0: common.v1.DataClassification
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_common_v1_classification_proto_depIdxs = []int32{
	1, // 0: common.v1.classification:extendee -> google.protobuf.FieldOptions
	0, // 1: common.v1.classification:type_name -> common.v1.DataClassification
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_classification_proto_init() }
func file_common_v1_classification_proto_init() {
	if File_common_v1_classification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_classification_proto_rawDesc), len(file_common_v1_classification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_classification_proto_goTypes,
		DependencyIndexes: file_common_v1_classification_proto_depIdxs,
		EnumInfos:         file_common_v1_classification_proto_enumTypes,
		ExtensionInfos:    file_common_v1_classification_proto_extTypes,
	}.Build()
	File_common_v1_classification_proto = out.File
	file_common_v1_classification_proto_goTypes = nil
	file_common_v1_classification_proto_depIdxs = nil
}
