// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/v1/surface.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Surface identifies the product or channel surface that originated a platform
// action. It is shared by runtime, audit, and product-facing services so
// callers do not invent drift-prone string labels.
type Surface int32

const (
	Surface_SURFACE_UNSPECIFIED Surface = 0
	Surface_SURFACE_ENSEMBLE    Surface = 1
	Surface_SURFACE_CHAT        Surface = 2
	Surface_SURFACE_MAESTRO     Surface = 3
	Surface_SURFACE_CONDUCTOR   Surface = 4
	Surface_SURFACE_SLACK       Surface = 5
	// SURFACE_EXTERNAL_AGENT identifies a third-party coding agent (Claude
	// Code, Cursor, or another external agent) driving Platform through a
	// non-Deixic surface. It is additive and wire-compatible: existing
	// callers keep matching on SURFACE_ENSEMBLE/CHAT/MAESTRO/CONDUCTOR/SLACK,
	// and every exhaustive Rust match must handle it deliberately rather than
	// fall through to SURFACE_UNSPECIFIED.
	Surface_SURFACE_EXTERNAL_AGENT Surface = 6
)

// Enum value maps for Surface.
var (
	Surface_name = map[int32]string{
		0: "SURFACE_UNSPECIFIED",
		1: "SURFACE_ENSEMBLE",
		2: "SURFACE_CHAT",
		3: "SURFACE_MAESTRO",
		4: "SURFACE_CONDUCTOR",
		5: "SURFACE_SLACK",
		6: "SURFACE_EXTERNAL_AGENT",
	}
	Surface_value = map[string]int32{
		"SURFACE_UNSPECIFIED":    0,
		"SURFACE_ENSEMBLE":       1,
		"SURFACE_CHAT":           2,
		"SURFACE_MAESTRO":        3,
		"SURFACE_CONDUCTOR":      4,
		"SURFACE_SLACK":          5,
		"SURFACE_EXTERNAL_AGENT": 6,
	}
)

func (x Surface) Enum() *Surface {
	p := new(Surface)
	*p = x
	return p
}

func (x Surface) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Surface) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_surface_proto_enumTypes[0].Descriptor()
}

func (Surface) Type() protoreflect.EnumType {
	return &file_common_v1_surface_proto_enumTypes[0]
}

func (x Surface) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Surface.Descriptor instead.
func (Surface) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_surface_proto_rawDescGZIP(), []int{0}
}

var File_common_v1_surface_proto protoreflect.FileDescriptor

const file_common_v1_surface_proto_rawDesc = "" +
	"\n" +
	"\x17common/v1/surface.proto\x12\tcommon.v1*\xa5\x01\n" +
	"\aSurface\x12\x17\n" +
	"\x13SURFACE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SURFACE_ENSEMBLE\x10\x01\x12\x10\n" +
	"\fSURFACE_CHAT\x10\x02\x12\x13\n" +
	"\x0fSURFACE_MAESTRO\x10\x03\x12\x15\n" +
	"\x11SURFACE_CONDUCTOR\x10\x04\x12\x11\n" +
	"\rSURFACE_SLACK\x10\x05\x12\x1a\n" +
	"\x16SURFACE_EXTERNAL_AGENT\x10\x06B7Z5github.com/evalops/platform/gen/go/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_surface_proto_rawDescOnce sync.Once
	file_common_v1_surface_proto_rawDescData []byte
)

func file_common_v1_surface_proto_rawDescGZIP() []byte {
	file_common_v1_surface_proto_rawDescOnce.Do(func() {
		file_common_v1_surface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_surface_proto_rawDesc), len(file_common_v1_surface_proto_rawDesc)))
	})
	return file_common_v1_surface_proto_rawDescData
}

var file_common_v1_surface_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_surface_proto_goTypes = []any{
	(Surface)(0), // 0: common.v1.Surface
}
var file_common_v1_surface_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_surface_proto_init() }
func file_common_v1_surface_proto_init() {
	if File_common_v1_surface_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_surface_proto_rawDesc), len(file_common_v1_surface_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_surface_proto_goTypes,
		DependencyIndexes: file_common_v1_surface_proto_depIdxs,
		EnumInfos:         file_common_v1_surface_proto_enumTypes,
	}.Build()
	File_common_v1_surface_proto = out.File
	file_common_v1_surface_proto_goTypes = nil
	file_common_v1_surface_proto_depIdxs = nil
}
