// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orbcontrol/v1/orb_control.proto

package orbcontrolv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/dx-corp/deixic-go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrbCommandKind is the first supported Platform-owned lifecycle command set.
type OrbCommandKind int32

const (
	OrbCommandKind_ORB_COMMAND_KIND_UNSPECIFIED OrbCommandKind = 0
	OrbCommandKind_ORB_COMMAND_KIND_WAKE        OrbCommandKind = 1
	OrbCommandKind_ORB_COMMAND_KIND_STOP        OrbCommandKind = 2
)

// Enum value maps for OrbCommandKind.
var (
	OrbCommandKind_name = map[int32]string{
		0: "ORB_COMMAND_KIND_UNSPECIFIED",
		1: "ORB_COMMAND_KIND_WAKE",
		2: "ORB_COMMAND_KIND_STOP",
	}
	OrbCommandKind_value = map[string]int32{
		"ORB_COMMAND_KIND_UNSPECIFIED": 0,
		"ORB_COMMAND_KIND_WAKE":        1,
		"ORB_COMMAND_KIND_STOP":        2,
	}
)

func (x OrbCommandKind) Enum() *OrbCommandKind {
	p := new(OrbCommandKind)
	*p = x
	return p
}

func (x OrbCommandKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrbCommandKind) Descriptor() protoreflect.EnumDescriptor {
	return file_orbcontrol_v1_orb_control_proto_enumTypes[0].Descriptor()
}

func (OrbCommandKind) Type() protoreflect.EnumType {
	return &file_orbcontrol_v1_orb_control_proto_enumTypes[0]
}

func (x OrbCommandKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrbCommandKind.Descriptor instead.
func (OrbCommandKind) EnumDescriptor() ([]byte, []int) {
	return file_orbcontrol_v1_orb_control_proto_rawDescGZIP(), []int{0}
}

// OrbObservedLifecycle is the runtime owner's customer-safe lifecycle state.
type OrbObservedLifecycle int32

const (
	OrbObservedLifecycle_ORB_OBSERVED_LIFECYCLE_UNSPECIFIED     OrbObservedLifecycle = 0
	OrbObservedLifecycle_ORB_OBSERVED_LIFECYCLE_SLEEPING        OrbObservedLifecycle = 1
	OrbObservedLifecycle_ORB_OBSERVED_LIFECYCLE_WAKING          OrbObservedLifecycle = 2
	OrbObservedLifecycle_ORB_OBSERVED_LIFECYCLE_READY           OrbObservedLifecycle = 3
	OrbObservedLifecycle_ORB_OBSERVED_LIFECYCLE_WORKING         OrbObservedLifecycle = 4
	OrbObservedLifecycle_ORB_OBSERVED_LIFECYCLE_WAITING_FOR_YOU OrbObservedLifecycle = 5
	OrbObservedLifecycle_ORB_OBSERVED_LIFECYCLE_RECOVERING      OrbObservedLifecycle = 6
	OrbObservedLifecycle_ORB_OBSERVED_LIFECYCLE_OFFLINE         OrbObservedLifecycle = 7
)

// Enum value maps for OrbObservedLifecycle.
var (
	OrbObservedLifecycle_name = map[int32]string{
		0: "ORB_OBSERVED_LIFECYCLE_UNSPECIFIED",
		1: "ORB_OBSERVED_LIFECYCLE_SLEEPING",
		2: "ORB_OBSERVED_LIFECYCLE_WAKING",
		3: "ORB_OBSERVED_LIFECYCLE_READY",
		4: "ORB_OBSERVED_LIFECYCLE_WORKING",
		5: "ORB_OBSERVED_LIFECYCLE_WAITING_FOR_YOU",
		6: "ORB_OBSERVED_LIFECYCLE_RECOVERING",
		7: "ORB_OBSERVED_LIFECYCLE_OFFLINE",
	}
	OrbObservedLifecycle_value = map[string]int32{
		"ORB_OBSERVED_LIFECYCLE_UNSPECIFIED":     0,
		"ORB_OBSERVED_LIFECYCLE_SLEEPING":        1,
		"ORB_OBSERVED_LIFECYCLE_WAKING":          2,
		"ORB_OBSERVED_LIFECYCLE_READY":           3,
		"ORB_OBSERVED_LIFECYCLE_WORKING":         4,
		"ORB_OBSERVED_LIFECYCLE_WAITING_FOR_YOU": 5,
		"ORB_OBSERVED_LIFECYCLE_RECOVERING":      6,
		"ORB_OBSERVED_LIFECYCLE_OFFLINE":         7,
	}
)

func (x OrbObservedLifecycle) Enum() *OrbObservedLifecycle {
	p := new(OrbObservedLifecycle)
	*p = x
	return p
}

func (x OrbObservedLifecycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrbObservedLifecycle) Descriptor() protoreflect.EnumDescriptor {
	return file_orbcontrol_v1_orb_control_proto_enumTypes[1].Descriptor()
}

func (OrbObservedLifecycle) Type() protoreflect.EnumType {
	return &file_orbcontrol_v1_orb_control_proto_enumTypes[1]
}

func (x OrbObservedLifecycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrbObservedLifecycle.Descriptor instead.
func (OrbObservedLifecycle) EnumDescriptor() ([]byte, []int) {
	return file_orbcontrol_v1_orb_control_proto_rawDescGZIP(), []int{1}
}

// OrbCommandAcceptance distinguishes a new acceptance from an exact replay.
type OrbCommandAcceptance int32

const (
	OrbCommandAcceptance_ORB_COMMAND_ACCEPTANCE_UNSPECIFIED OrbCommandAcceptance = 0
	OrbCommandAcceptance_ORB_COMMAND_ACCEPTANCE_ACCEPTED    OrbCommandAcceptance = 1
	OrbCommandAcceptance_ORB_COMMAND_ACCEPTANCE_REPLAYED    OrbCommandAcceptance = 2
	OrbCommandAcceptance_ORB_COMMAND_ACCEPTANCE_REJECTED    OrbCommandAcceptance = 3
)

// Enum value maps for OrbCommandAcceptance.
var (
	OrbCommandAcceptance_name = map[int32]string{
		0: "ORB_COMMAND_ACCEPTANCE_UNSPECIFIED",
		1: "ORB_COMMAND_ACCEPTANCE_ACCEPTED",
		2: "ORB_COMMAND_ACCEPTANCE_REPLAYED",
		3: "ORB_COMMAND_ACCEPTANCE_REJECTED",
	}
	OrbCommandAcceptance_value = map[string]int32{
		"ORB_COMMAND_ACCEPTANCE_UNSPECIFIED": 0,
		"ORB_COMMAND_ACCEPTANCE_ACCEPTED":    1,
		"ORB_COMMAND_ACCEPTANCE_REPLAYED":    2,
		"ORB_COMMAND_ACCEPTANCE_REJECTED":    3,
	}
)

func (x OrbCommandAcceptance) Enum() *OrbCommandAcceptance {
	p := new(OrbCommandAcceptance)
	*p = x
	return p
}

func (x OrbCommandAcceptance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrbCommandAcceptance) Descriptor() protoreflect.EnumDescriptor {
	return file_orbcontrol_v1_orb_control_proto_enumTypes[2].Descriptor()
}

func (OrbCommandAcceptance) Type() protoreflect.EnumType {
	return &file_orbcontrol_v1_orb_control_proto_enumTypes[2]
}

func (x OrbCommandAcceptance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrbCommandAcceptance.Descriptor instead.
func (OrbCommandAcceptance) EnumDescriptor() ([]byte, []int) {
	return file_orbcontrol_v1_orb_control_proto_rawDescGZIP(), []int{2}
}

// OrbControlEventKind identifies durable owner observations.
type OrbControlEventKind int32

const (
	OrbControlEventKind_ORB_CONTROL_EVENT_KIND_UNSPECIFIED       OrbControlEventKind = 0
	OrbControlEventKind_ORB_CONTROL_EVENT_KIND_SNAPSHOT          OrbControlEventKind = 1
	OrbControlEventKind_ORB_CONTROL_EVENT_KIND_COMMAND_ACCEPTED  OrbControlEventKind = 2
	OrbControlEventKind_ORB_CONTROL_EVENT_KIND_LIFECYCLE_CHANGED OrbControlEventKind = 3
	OrbControlEventKind_ORB_CONTROL_EVENT_KIND_COMMAND_COMPLETED OrbControlEventKind = 4
	OrbControlEventKind_ORB_CONTROL_EVENT_KIND_COMMAND_FAILED    OrbControlEventKind = 5
)

// Enum value maps for OrbControlEventKind.
var (
	OrbControlEventKind_name = map[int32]string{
		0: "ORB_CONTROL_EVENT_KIND_UNSPECIFIED",
		1: "ORB_CONTROL_EVENT_KIND_SNAPSHOT",
		2: "ORB_CONTROL_EVENT_KIND_COMMAND_ACCEPTED",
		3: "ORB_CONTROL_EVENT_KIND_LIFECYCLE_CHANGED",
		4: "ORB_CONTROL_EVENT_KIND_COMMAND_COMPLETED",
		5: "ORB_CONTROL_EVENT_KIND_COMMAND_FAILED",
	}
	OrbControlEventKind_value = map[string]int32{
		"ORB_CONTROL_EVENT_KIND_UNSPECIFIED":       0,
		"ORB_CONTROL_EVENT_KIND_SNAPSHOT":          1,
		"ORB_CONTROL_EVENT_KIND_COMMAND_ACCEPTED":  2,
		"ORB_CONTROL_EVENT_KIND_LIFECYCLE_CHANGED": 3,
		"ORB_CONTROL_EVENT_KIND_COMMAND_COMPLETED": 4,
		"ORB_CONTROL_EVENT_KIND_COMMAND_FAILED":    5,
	}
)

func (x OrbControlEventKind) Enum() *OrbControlEventKind {
	p := new(OrbControlEventKind)
	*p = x
	return p
}

func (x OrbControlEventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrbControlEventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_orbcontrol_v1_orb_control_proto_enumTypes[3].Descriptor()
}

func (OrbControlEventKind) Type() protoreflect.EnumType {
	return &file_orbcontrol_v1_orb_control_proto_enumTypes[3]
}

func (x OrbControlEventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrbControlEventKind.Descriptor instead.
func (OrbControlEventKind) EnumDescriptor() ([]byte, []int) {
	return file_orbcontrol_v1_orb_control_proto_rawDescGZIP(), []int{3}
}

// OrbCommand is the normalized mutation payload persisted by both planes.
type OrbCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          OrbCommandKind         `protobuf:"varint,1,opt,name=kind,proto3,enum=orbcontrol.v1.OrbCommandKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrbCommand) Reset() {
	*x = OrbCommand{}
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrbCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrbCommand) ProtoMessage() {}

func (x *OrbCommand) ProtoReflect() protoreflect.Message {
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrbCommand.ProtoReflect.Descriptor instead.
func (*OrbCommand) Descriptor() ([]byte, []int) {
	return file_orbcontrol_v1_orb_control_proto_rawDescGZIP(), []int{0}
}

func (x *OrbCommand) GetKind() OrbCommandKind {
	if x != nil {
		return x.Kind
	}
	return OrbCommandKind_ORB_COMMAND_KIND_UNSPECIFIED
}

// SubmitOrbCommandRequest carries one exact tenant-scoped owner command.
type SubmitOrbCommandRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId     string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	WorkspaceId        string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	TargetId           string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	IdempotencyKey     string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	LineageId          string                 `protobuf:"bytes,5,opt,name=lineage_id,json=lineageId,proto3" json:"lineage_id,omitempty"`
	OperationId        string                 `protobuf:"bytes,6,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ExpectedGeneration uint64                 `protobuf:"varint,7,opt,name=expected_generation,json=expectedGeneration,proto3" json:"expected_generation,omitempty"`
	Command            *OrbCommand            `protobuf:"bytes,8,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubmitOrbCommandRequest) Reset() {
	*x = SubmitOrbCommandRequest{}
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrbCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrbCommandRequest) ProtoMessage() {}

func (x *SubmitOrbCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrbCommandRequest.ProtoReflect.Descriptor instead.
func (*SubmitOrbCommandRequest) Descriptor() ([]byte, []int) {
	return file_orbcontrol_v1_orb_control_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitOrbCommandRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SubmitOrbCommandRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SubmitOrbCommandRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *SubmitOrbCommandRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SubmitOrbCommandRequest) GetLineageId() string {
	if x != nil {
		return x.LineageId
	}
	return ""
}

func (x *SubmitOrbCommandRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *SubmitOrbCommandRequest) GetExpectedGeneration() uint64 {
	if x != nil {
		return x.ExpectedGeneration
	}
	return 0
}

func (x *SubmitOrbCommandRequest) GetCommand() *OrbCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

// SubmitOrbCommandResponse acknowledges ownership without claiming completion.
type SubmitOrbCommandResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Acceptance         OrbCommandAcceptance   `protobuf:"varint,1,opt,name=acceptance,proto3,enum=orbcontrol.v1.OrbCommandAcceptance" json:"acceptance,omitempty"`
	CommandId          string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	OperationId        string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	IdempotencyKey     string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	AcceptedGeneration uint64                 `protobuf:"varint,5,opt,name=accepted_generation,json=acceptedGeneration,proto3" json:"accepted_generation,omitempty"`
	ObservedRevision   uint64                 `protobuf:"varint,6,opt,name=observed_revision,json=observedRevision,proto3" json:"observed_revision,omitempty"`
	EventSequence      uint64                 `protobuf:"varint,7,opt,name=event_sequence,json=eventSequence,proto3" json:"event_sequence,omitempty"`
	ReasonCode         string                 `protobuf:"bytes,8,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubmitOrbCommandResponse) Reset() {
	*x = SubmitOrbCommandResponse{}
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrbCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrbCommandResponse) ProtoMessage() {}

func (x *SubmitOrbCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrbCommandResponse.ProtoReflect.Descriptor instead.
func (*SubmitOrbCommandResponse) Descriptor() ([]byte, []int) {
	return file_orbcontrol_v1_orb_control_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitOrbCommandResponse) GetAcceptance() OrbCommandAcceptance {
	if x != nil {
		return x.Acceptance
	}
	return OrbCommandAcceptance_ORB_COMMAND_ACCEPTANCE_UNSPECIFIED
}

func (x *SubmitOrbCommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *SubmitOrbCommandResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *SubmitOrbCommandResponse) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SubmitOrbCommandResponse) GetAcceptedGeneration() uint64 {
	if x != nil {
		return x.AcceptedGeneration
	}
	return 0
}

func (x *SubmitOrbCommandResponse) GetObservedRevision() uint64 {
	if x != nil {
		return x.ObservedRevision
	}
	return 0
}

func (x *SubmitOrbCommandResponse) GetEventSequence() uint64 {
	if x != nil {
		return x.EventSequence
	}
	return 0
}

func (x *SubmitOrbCommandResponse) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

// GetOrbObservedStateRequest selects one tenant-scoped runtime target.
type GetOrbObservedStateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	WorkspaceId    string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	TargetId       string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrbObservedStateRequest) Reset() {
	*x = GetOrbObservedStateRequest{}
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrbObservedStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrbObservedStateRequest) ProtoMessage() {}

func (x *GetOrbObservedStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrbObservedStateRequest.ProtoReflect.Descriptor instead.
func (*GetOrbObservedStateRequest) Descriptor() ([]byte, []int) {
	return file_orbcontrol_v1_orb_control_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrbObservedStateRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetOrbObservedStateRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GetOrbObservedStateRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

// OrbObservedState is the authoritative runtime projection for one target.
type OrbObservedState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TargetId          string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	DisplayName       string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Lifecycle         OrbObservedLifecycle   `protobuf:"varint,3,opt,name=lifecycle,proto3,enum=orbcontrol.v1.OrbObservedLifecycle" json:"lifecycle,omitempty"`
	Generation        uint64                 `protobuf:"varint,4,opt,name=generation,proto3" json:"generation,omitempty"`
	ObservedRevision  uint64                 `protobuf:"varint,5,opt,name=observed_revision,json=observedRevision,proto3" json:"observed_revision,omitempty"`
	LastEventSequence uint64                 `protobuf:"varint,6,opt,name=last_event_sequence,json=lastEventSequence,proto3" json:"last_event_sequence,omitempty"`
	ResidentAgent     string                 `protobuf:"bytes,7,opt,name=resident_agent,json=residentAgent,proto3" json:"resident_agent,omitempty"`
	Provisioner       string                 `protobuf:"bytes,8,opt,name=provisioner,proto3" json:"provisioner,omitempty"`
	ActiveOperationId string                 `protobuf:"bytes,9,opt,name=active_operation_id,json=activeOperationId,proto3" json:"active_operation_id,omitempty"`
	ObservedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrbObservedState) Reset() {
	*x = OrbObservedState{}
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrbObservedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrbObservedState) ProtoMessage() {}

func (x *OrbObservedState) ProtoReflect() protoreflect.Message {
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrbObservedState.ProtoReflect.Descriptor instead.
func (*OrbObservedState) Descriptor() ([]byte, []int) {
	return file_orbcontrol_v1_orb_control_proto_rawDescGZIP(), []int{4}
}

func (x *OrbObservedState) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *OrbObservedState) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *OrbObservedState) GetLifecycle() OrbObservedLifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return OrbObservedLifecycle_ORB_OBSERVED_LIFECYCLE_UNSPECIFIED
}

func (x *OrbObservedState) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *OrbObservedState) GetObservedRevision() uint64 {
	if x != nil {
		return x.ObservedRevision
	}
	return 0
}

func (x *OrbObservedState) GetLastEventSequence() uint64 {
	if x != nil {
		return x.LastEventSequence
	}
	return 0
}

func (x *OrbObservedState) GetResidentAgent() string {
	if x != nil {
		return x.ResidentAgent
	}
	return ""
}

func (x *OrbObservedState) GetProvisioner() string {
	if x != nil {
		return x.Provisioner
	}
	return ""
}

func (x *OrbObservedState) GetActiveOperationId() string {
	if x != nil {
		return x.ActiveOperationId
	}
	return ""
}

func (x *OrbObservedState) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

// GetOrbObservedStateResponse returns one authoritative runtime projection.
type GetOrbObservedStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *OrbObservedState      `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrbObservedStateResponse) Reset() {
	*x = GetOrbObservedStateResponse{}
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrbObservedStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrbObservedStateResponse) ProtoMessage() {}

func (x *GetOrbObservedStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrbObservedStateResponse.ProtoReflect.Descriptor instead.
func (*GetOrbObservedStateResponse) Descriptor() ([]byte, []int) {
	return file_orbcontrol_v1_orb_control_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrbObservedStateResponse) GetState() *OrbObservedState {
	if x != nil {
		return x.State
	}
	return nil
}

// OrbControlEvent is one workspace-ordered observed-state transition.
type OrbControlEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Sequence         uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	EventId          string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TargetId         string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Generation       uint64                 `protobuf:"varint,4,opt,name=generation,proto3" json:"generation,omitempty"`
	ObservedRevision uint64                 `protobuf:"varint,5,opt,name=observed_revision,json=observedRevision,proto3" json:"observed_revision,omitempty"`
	Kind             OrbControlEventKind    `protobuf:"varint,6,opt,name=kind,proto3,enum=orbcontrol.v1.OrbControlEventKind" json:"kind,omitempty"`
	State            *OrbObservedState      `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	OperationId      string                 `protobuf:"bytes,8,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	CommandId        string                 `protobuf:"bytes,9,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ReasonCode       string                 `protobuf:"bytes,10,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	OccurredAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrbControlEvent) Reset() {
	*x = OrbControlEvent{}
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrbControlEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrbControlEvent) ProtoMessage() {}

func (x *OrbControlEvent) ProtoReflect() protoreflect.Message {
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrbControlEvent.ProtoReflect.Descriptor instead.
func (*OrbControlEvent) Descriptor() ([]byte, []int) {
	return file_orbcontrol_v1_orb_control_proto_rawDescGZIP(), []int{6}
}

func (x *OrbControlEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *OrbControlEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *OrbControlEvent) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *OrbControlEvent) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *OrbControlEvent) GetObservedRevision() uint64 {
	if x != nil {
		return x.ObservedRevision
	}
	return 0
}

func (x *OrbControlEvent) GetKind() OrbControlEventKind {
	if x != nil {
		return x.Kind
	}
	return OrbControlEventKind_ORB_CONTROL_EVENT_KIND_UNSPECIFIED
}

func (x *OrbControlEvent) GetState() *OrbObservedState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *OrbControlEvent) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OrbControlEvent) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *OrbControlEvent) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *OrbControlEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// StreamOrbEventsRequest resumes a tenant-wide cursor after one sequence.
type StreamOrbEventsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	WorkspaceId    string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	AfterSequence  uint64                 `protobuf:"varint,3,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	Limit          uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamOrbEventsRequest) Reset() {
	*x = StreamOrbEventsRequest{}
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrbEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrbEventsRequest) ProtoMessage() {}

func (x *StreamOrbEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrbEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamOrbEventsRequest) Descriptor() ([]byte, []int) {
	return file_orbcontrol_v1_orb_control_proto_rawDescGZIP(), []int{7}
}

func (x *StreamOrbEventsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *StreamOrbEventsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *StreamOrbEventsRequest) GetAfterSequence() uint64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

func (x *StreamOrbEventsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// StreamOrbEventsResponse is a bounded durable cursor page.
type StreamOrbEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*OrbControlEvent     `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextSequence  uint64                 `protobuf:"varint,2,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOrbEventsResponse) Reset() {
	*x = StreamOrbEventsResponse{}
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrbEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrbEventsResponse) ProtoMessage() {}

func (x *StreamOrbEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orbcontrol_v1_orb_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrbEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamOrbEventsResponse) Descriptor() ([]byte, []int) {
	return file_orbcontrol_v1_orb_control_proto_rawDescGZIP(), []int{8}
}

func (x *StreamOrbEventsResponse) GetEvents() []*OrbControlEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *StreamOrbEventsResponse) GetNextSequence() uint64 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

func (x *StreamOrbEventsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_orbcontrol_v1_orb_control_proto protoreflect.FileDescriptor

const file_orbcontrol_v1_orb_control_proto_rawDesc = "" +
	"\n" +
	"\x1forbcontrol/v1/orb_control.proto\x12\rorbcontrol.v1\x1a\x1bbuf/validate/validate.proto\x1a\x15common/v1/authz.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"K\n" +
	"\n" +
	"OrbCommand\x12=\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1d.orbcontrol.v1.OrbCommandKindB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04kind\"\x91\x03\n" +
	"\x17SubmitOrbCommandRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12*\n" +
	"\fworkspace_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vworkspaceId\x12$\n" +
	"\ttarget_id\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\btargetId\x120\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eidempotencyKey\x12&\n" +
	"\n" +
	"lineage_id\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tlineageId\x12*\n" +
	"\foperation_id\x18\x06 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\voperationId\x12/\n" +
	"\x13expected_generation\x18\a \x01(\x04R\x12expectedGeneration\x12;\n" +
	"\acommand\x18\b \x01(\v2\x19.orbcontrol.v1.OrbCommandB\x06\xbaH\x03\xc8\x01\x01R\acommand\"\xfa\x02\n" +
	"\x18SubmitOrbCommandResponse\x12M\n" +
	"\n" +
	"acceptance\x18\x01 \x01(\x0e2#.orbcontrol.v1.OrbCommandAcceptanceB\b\xbaH\x05\x82\x01\x02\x10\x01R\n" +
	"acceptance\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12/\n" +
	"\x13accepted_generation\x18\x05 \x01(\x04R\x12acceptedGeneration\x12+\n" +
	"\x11observed_revision\x18\x06 \x01(\x04R\x10observedRevision\x12%\n" +
	"\x0eevent_sequence\x18\a \x01(\x04R\reventSequence\x12\x1f\n" +
	"\vreason_code\x18\b \x01(\tR\n" +
	"reasonCode\"\xa0\x01\n" +
	"\x1aGetOrbObservedStateRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12*\n" +
	"\fworkspace_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vworkspaceId\x12$\n" +
	"\ttarget_id\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\btargetId\"\xd2\x03\n" +
	"\x10OrbObservedState\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12K\n" +
	"\tlifecycle\x18\x03 \x01(\x0e2#.orbcontrol.v1.OrbObservedLifecycleB\b\xbaH\x05\x82\x01\x02\x10\x01R\tlifecycle\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\x04R\n" +
	"generation\x12+\n" +
	"\x11observed_revision\x18\x05 \x01(\x04R\x10observedRevision\x12.\n" +
	"\x13last_event_sequence\x18\x06 \x01(\x04R\x11lastEventSequence\x12%\n" +
	"\x0eresident_agent\x18\a \x01(\tR\rresidentAgent\x12 \n" +
	"\vprovisioner\x18\b \x01(\tR\vprovisioner\x12.\n" +
	"\x13active_operation_id\x18\t \x01(\tR\x11activeOperationId\x12;\n" +
	"\vobserved_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"\\\n" +
	"\x1bGetOrbObservedStateResponse\x12=\n" +
	"\x05state\x18\x01 \x01(\v2\x1f.orbcontrol.v1.OrbObservedStateB\x06\xbaH\x03\xc8\x01\x01R\x05state\"\xcb\x03\n" +
	"\x0fOrbControlEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\x04R\n" +
	"generation\x12+\n" +
	"\x11observed_revision\x18\x05 \x01(\x04R\x10observedRevision\x12@\n" +
	"\x04kind\x18\x06 \x01(\x0e2\".orbcontrol.v1.OrbControlEventKindB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04kind\x125\n" +
	"\x05state\x18\a \x01(\v2\x1f.orbcontrol.v1.OrbObservedStateR\x05state\x12!\n" +
	"\foperation_id\x18\b \x01(\tR\voperationId\x12\x1d\n" +
	"\n" +
	"command_id\x18\t \x01(\tR\tcommandId\x12\x1f\n" +
	"\vreason_code\x18\n" +
	" \x01(\tR\n" +
	"reasonCode\x12;\n" +
	"\voccurred_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xbd\x01\n" +
	"\x16StreamOrbEventsRequest\x120\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eorganizationId\x12*\n" +
	"\fworkspace_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vworkspaceId\x12%\n" +
	"\x0eafter_sequence\x18\x03 \x01(\x04R\rafterSequence\x12\x1e\n" +
	"\x05limit\x18\x04 \x01(\rB\b\xbaH\x05*\x03\x18\xf4\x03R\x05limit\"\x9c\x01\n" +
	"\x17StreamOrbEventsResponse\x12A\n" +
	"\x06events\x18\x01 \x03(\v2\x1e.orbcontrol.v1.OrbControlEventB\t\xbaH\x06\x92\x01\x03\x10\xf4\x03R\x06events\x12#\n" +
	"\rnext_sequence\x18\x02 \x01(\x04R\fnextSequence\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore*h\n" +
	"\x0eOrbCommandKind\x12 \n" +
	"\x1cORB_COMMAND_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ORB_COMMAND_KIND_WAKE\x10\x01\x12\x19\n" +
	"\x15ORB_COMMAND_KIND_STOP\x10\x02*\xc3\x02\n" +
	"\x14OrbObservedLifecycle\x12&\n" +
	"\"ORB_OBSERVED_LIFECYCLE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fORB_OBSERVED_LIFECYCLE_SLEEPING\x10\x01\x12!\n" +
	"\x1dORB_OBSERVED_LIFECYCLE_WAKING\x10\x02\x12 \n" +
	"\x1cORB_OBSERVED_LIFECYCLE_READY\x10\x03\x12\"\n" +
	"\x1eORB_OBSERVED_LIFECYCLE_WORKING\x10\x04\x12*\n" +
	"&ORB_OBSERVED_LIFECYCLE_WAITING_FOR_YOU\x10\x05\x12%\n" +
	"!ORB_OBSERVED_LIFECYCLE_RECOVERING\x10\x06\x12\"\n" +
	"\x1eORB_OBSERVED_LIFECYCLE_OFFLINE\x10\a*\xad\x01\n" +
	"\x14OrbCommandAcceptance\x12&\n" +
	"\"ORB_COMMAND_ACCEPTANCE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fORB_COMMAND_ACCEPTANCE_ACCEPTED\x10\x01\x12#\n" +
	"\x1fORB_COMMAND_ACCEPTANCE_REPLAYED\x10\x02\x12#\n" +
	"\x1fORB_COMMAND_ACCEPTANCE_REJECTED\x10\x03*\x96\x02\n" +
	"\x13OrbControlEventKind\x12&\n" +
	"\"ORB_CONTROL_EVENT_KIND_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fORB_CONTROL_EVENT_KIND_SNAPSHOT\x10\x01\x12+\n" +
	"'ORB_CONTROL_EVENT_KIND_COMMAND_ACCEPTED\x10\x02\x12,\n" +
	"(ORB_CONTROL_EVENT_KIND_LIFECYCLE_CHANGED\x10\x03\x12,\n" +
	"(ORB_CONTROL_EVENT_KIND_COMMAND_COMPLETED\x10\x04\x12)\n" +
	"%ORB_CONTROL_EVENT_KIND_COMMAND_FAILED\x10\x052\x8a\x04\n" +
	"\x16OrbControlOwnerService\x12\xa1\x01\n" +
	"\x10SubmitOrbCommand\x12&.orbcontrol.v1.SubmitOrbCommandRequest\x1a'.orbcontrol.v1.SubmitOrbCommandResponse\"<\xca\xf3\x18\x11orb:control:owner\xd2\xf3\x18\fworkspace_id\xd8\xf3\x18\x03\xea\xf3\x18\x0forganization_id\x12\xaa\x01\n" +
	"\x13GetOrbObservedState\x12).orbcontrol.v1.GetOrbObservedStateRequest\x1a*.orbcontrol.v1.GetOrbObservedStateResponse\"<\xca\xf3\x18\x11orb:control:owner\xd2\xf3\x18\fworkspace_id\xd8\xf3\x18\x01\xea\xf3\x18\x0forganization_id\x12\x9e\x01\n" +
	"\x0fStreamOrbEvents\x12%.orbcontrol.v1.StreamOrbEventsRequest\x1a&.orbcontrol.v1.StreamOrbEventsResponse\"<\xca\xf3\x18\x11orb:control:owner\xd2\xf3\x18\fworkspace_id\xd8\xf3\x18\x01\xea\xf3\x18\x0forganization_idB?Z=github.com/evalops/platform/gen/go/orbcontrol/v1;orbcontrolv1b\x06proto3"

var (
	file_orbcontrol_v1_orb_control_proto_rawDescOnce sync.Once
	file_orbcontrol_v1_orb_control_proto_rawDescData []byte
)

func file_orbcontrol_v1_orb_control_proto_rawDescGZIP() []byte {
	file_orbcontrol_v1_orb_control_proto_rawDescOnce.Do(func() {
		file_orbcontrol_v1_orb_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orbcontrol_v1_orb_control_proto_rawDesc), len(file_orbcontrol_v1_orb_control_proto_rawDesc)))
	})
	return file_orbcontrol_v1_orb_control_proto_rawDescData
}

var file_orbcontrol_v1_orb_control_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_orbcontrol_v1_orb_control_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_orbcontrol_v1_orb_control_proto_goTypes = []any{
	(OrbCommandKind)(0),                 // 0: orbcontrol.v1.OrbCommandKind
	(OrbObservedLifecycle)(0),           // 1: orbcontrol.v1.OrbObservedLifecycle
	(OrbCommandAcceptance)(0),           // 2: orbcontrol.v1.OrbCommandAcceptance
	(OrbControlEventKind)(0),            // 3: orbcontrol.v1.OrbControlEventKind
	(*OrbCommand)(nil),                  // 4: orbcontrol.v1.OrbCommand
	(*SubmitOrbCommandRequest)(nil),     // 5: orbcontrol.v1.SubmitOrbCommandRequest
	(*SubmitOrbCommandResponse)(nil),    // 6: orbcontrol.v1.SubmitOrbCommandResponse
	(*GetOrbObservedStateRequest)(nil),  // 7: orbcontrol.v1.GetOrbObservedStateRequest
	(*OrbObservedState)(nil),            // 8: orbcontrol.v1.OrbObservedState
	(*GetOrbObservedStateResponse)(nil), // 9: orbcontrol.v1.GetOrbObservedStateResponse
	(*OrbControlEvent)(nil),             // 10: orbcontrol.v1.OrbControlEvent
	(*StreamOrbEventsRequest)(nil),      // 11: orbcontrol.v1.StreamOrbEventsRequest
	(*StreamOrbEventsResponse)(nil),     // 12: orbcontrol.v1.StreamOrbEventsResponse
	(*timestamppb.Timestamp)(nil),       // 13: google.protobuf.Timestamp
}
var file_orbcontrol_v1_orb_control_proto_depIdxs = []int32{
	0,  // 0: orbcontrol.v1.OrbCommand.kind:type_name -> orbcontrol.v1.OrbCommandKind
	4,  // 1: orbcontrol.v1.SubmitOrbCommandRequest.command:type_name -> orbcontrol.v1.OrbCommand
	2,  // 2: orbcontrol.v1.SubmitOrbCommandResponse.acceptance:type_name -> orbcontrol.v1.OrbCommandAcceptance
	1,  // 3: orbcontrol.v1.OrbObservedState.lifecycle:type_name -> orbcontrol.v1.OrbObservedLifecycle
	13, // 4: orbcontrol.v1.OrbObservedState.observed_at:type_name -> google.protobuf.Timestamp
	8,  // 5: orbcontrol.v1.GetOrbObservedStateResponse.state:type_name -> orbcontrol.v1.OrbObservedState
	3,  // 6: orbcontrol.v1.OrbControlEvent.kind:type_name -> orbcontrol.v1.OrbControlEventKind
	8,  // 7: orbcontrol.v1.OrbControlEvent.state:type_name -> orbcontrol.v1.OrbObservedState
	13, // 8: orbcontrol.v1.OrbControlEvent.occurred_at:type_name -> google.protobuf.Timestamp
	10, // 9: orbcontrol.v1.StreamOrbEventsResponse.events:type_name -> orbcontrol.v1.OrbControlEvent
	5,  // 10: orbcontrol.v1.OrbControlOwnerService.SubmitOrbCommand:input_type -> orbcontrol.v1.SubmitOrbCommandRequest
	7,  // 11: orbcontrol.v1.OrbControlOwnerService.GetOrbObservedState:input_type -> orbcontrol.v1.GetOrbObservedStateRequest
	11, // 12: orbcontrol.v1.OrbControlOwnerService.StreamOrbEvents:input_type -> orbcontrol.v1.StreamOrbEventsRequest
	6,  // 13: orbcontrol.v1.OrbControlOwnerService.SubmitOrbCommand:output_type -> orbcontrol.v1.SubmitOrbCommandResponse
	9,  // 14: orbcontrol.v1.OrbControlOwnerService.GetOrbObservedState:output_type -> orbcontrol.v1.GetOrbObservedStateResponse
	12, // 15: orbcontrol.v1.OrbControlOwnerService.StreamOrbEvents:output_type -> orbcontrol.v1.StreamOrbEventsResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_orbcontrol_v1_orb_control_proto_init() }
func file_orbcontrol_v1_orb_control_proto_init() {
	if File_orbcontrol_v1_orb_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orbcontrol_v1_orb_control_proto_rawDesc), len(file_orbcontrol_v1_orb_control_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orbcontrol_v1_orb_control_proto_goTypes,
		DependencyIndexes: file_orbcontrol_v1_orb_control_proto_depIdxs,
		EnumInfos:         file_orbcontrol_v1_orb_control_proto_enumTypes,
		MessageInfos:      file_orbcontrol_v1_orb_control_proto_msgTypes,
	}.Build()
	File_orbcontrol_v1_orb_control_proto = out.File
	file_orbcontrol_v1_orb_control_proto_goTypes = nil
	file_orbcontrol_v1_orb_control_proto_depIdxs = nil
}
