// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: deixicpublic/v1/sdk.proto

package deixicpublicv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dx-corp/deixic-go/deixicpublic/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DeixicPublicServiceName is the fully-qualified name of the DeixicPublicService service.
	DeixicPublicServiceName = "deixicpublic.v1.DeixicPublicService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DeixicPublicServiceGetThreadProcedure is the fully-qualified name of the DeixicPublicService's
	// GetThread RPC.
	DeixicPublicServiceGetThreadProcedure = "/deixicpublic.v1.DeixicPublicService/GetThread"
	// DeixicPublicServiceListThreadsProcedure is the fully-qualified name of the DeixicPublicService's
	// ListThreads RPC.
	DeixicPublicServiceListThreadsProcedure = "/deixicpublic.v1.DeixicPublicService/ListThreads"
	// DeixicPublicServiceRenameThreadProcedure is the fully-qualified name of the DeixicPublicService's
	// RenameThread RPC.
	DeixicPublicServiceRenameThreadProcedure = "/deixicpublic.v1.DeixicPublicService/RenameThread"
	// DeixicPublicServiceArchiveThreadProcedure is the fully-qualified name of the
	// DeixicPublicService's ArchiveThread RPC.
	DeixicPublicServiceArchiveThreadProcedure = "/deixicpublic.v1.DeixicPublicService/ArchiveThread"
	// DeixicPublicServiceListEventsProcedure is the fully-qualified name of the DeixicPublicService's
	// ListEvents RPC.
	DeixicPublicServiceListEventsProcedure = "/deixicpublic.v1.DeixicPublicService/ListEvents"
	// DeixicPublicServiceWatchEventsProcedure is the fully-qualified name of the DeixicPublicService's
	// WatchEvents RPC.
	DeixicPublicServiceWatchEventsProcedure = "/deixicpublic.v1.DeixicPublicService/WatchEvents"
	// DeixicPublicServiceSubmitTaskProcedure is the fully-qualified name of the DeixicPublicService's
	// SubmitTask RPC.
	DeixicPublicServiceSubmitTaskProcedure = "/deixicpublic.v1.DeixicPublicService/SubmitTask"
	// DeixicPublicServiceInterruptTaskProcedure is the fully-qualified name of the
	// DeixicPublicService's InterruptTask RPC.
	DeixicPublicServiceInterruptTaskProcedure = "/deixicpublic.v1.DeixicPublicService/InterruptTask"
	// DeixicPublicServiceRespondToRequestProcedure is the fully-qualified name of the
	// DeixicPublicService's RespondToRequest RPC.
	DeixicPublicServiceRespondToRequestProcedure = "/deixicpublic.v1.DeixicPublicService/RespondToRequest"
	// DeixicPublicServiceGetReceiptProcedure is the fully-qualified name of the DeixicPublicService's
	// GetReceipt RPC.
	DeixicPublicServiceGetReceiptProcedure = "/deixicpublic.v1.DeixicPublicService/GetReceipt"
	// DeixicPublicServiceResolveReceiptActionProcedure is the fully-qualified name of the
	// DeixicPublicService's ResolveReceiptAction RPC.
	DeixicPublicServiceResolveReceiptActionProcedure = "/deixicpublic.v1.DeixicPublicService/ResolveReceiptAction"
	// DeixicPublicServiceGetModelReadinessProcedure is the fully-qualified name of the
	// DeixicPublicService's GetModelReadiness RPC.
	DeixicPublicServiceGetModelReadinessProcedure = "/deixicpublic.v1.DeixicPublicService/GetModelReadiness"
	// DeixicPublicServiceGetClientSetupProcedure is the fully-qualified name of the
	// DeixicPublicService's GetClientSetup RPC.
	DeixicPublicServiceGetClientSetupProcedure = "/deixicpublic.v1.DeixicPublicService/GetClientSetup"
	// DeixicPublicServiceSubmitIssueReportProcedure is the fully-qualified name of the
	// DeixicPublicService's SubmitIssueReport RPC.
	DeixicPublicServiceSubmitIssueReportProcedure = "/deixicpublic.v1.DeixicPublicService/SubmitIssueReport"
	// DeixicPublicServiceCreateBusinessObjectProcedure is the fully-qualified name of the
	// DeixicPublicService's CreateBusinessObject RPC.
	DeixicPublicServiceCreateBusinessObjectProcedure = "/deixicpublic.v1.DeixicPublicService/CreateBusinessObject"
	// DeixicPublicServiceGetBusinessObjectProcedure is the fully-qualified name of the
	// DeixicPublicService's GetBusinessObject RPC.
	DeixicPublicServiceGetBusinessObjectProcedure = "/deixicpublic.v1.DeixicPublicService/GetBusinessObject"
	// DeixicPublicServiceUpdateBusinessObjectProcedure is the fully-qualified name of the
	// DeixicPublicService's UpdateBusinessObject RPC.
	DeixicPublicServiceUpdateBusinessObjectProcedure = "/deixicpublic.v1.DeixicPublicService/UpdateBusinessObject"
	// DeixicPublicServiceDeleteBusinessObjectProcedure is the fully-qualified name of the
	// DeixicPublicService's DeleteBusinessObject RPC.
	DeixicPublicServiceDeleteBusinessObjectProcedure = "/deixicpublic.v1.DeixicPublicService/DeleteBusinessObject"
)

// DeixicPublicServiceClient is a client for the deixicpublic.v1.DeixicPublicService service.
type DeixicPublicServiceClient interface {
	GetThread(context.Context, *connect.Request[v1.GetThreadRequest]) (*connect.Response[v1.GetThreadResponse], error)
	ListThreads(context.Context, *connect.Request[v1.ListThreadsRequest]) (*connect.Response[v1.ListThreadsResponse], error)
	RenameThread(context.Context, *connect.Request[v1.RenameThreadRequest]) (*connect.Response[v1.RenameThreadResponse], error)
	ArchiveThread(context.Context, *connect.Request[v1.ArchiveThreadRequest]) (*connect.Response[v1.ArchiveThreadResponse], error)
	ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error)
	WatchEvents(context.Context, *connect.Request[v1.WatchEventsRequest]) (*connect.ServerStreamForClient[v1.WatchEventsResponse], error)
	SubmitTask(context.Context, *connect.Request[v1.SubmitTaskRequest]) (*connect.Response[v1.SubmitTaskResponse], error)
	InterruptTask(context.Context, *connect.Request[v1.InterruptTaskRequest]) (*connect.Response[v1.InterruptTaskResponse], error)
	RespondToRequest(context.Context, *connect.Request[v1.RespondToRequestRequest]) (*connect.Response[v1.RespondToRequestResponse], error)
	GetReceipt(context.Context, *connect.Request[v1.GetReceiptRequest]) (*connect.Response[v1.GetReceiptResponse], error)
	ResolveReceiptAction(context.Context, *connect.Request[v1.ResolveReceiptActionRequest]) (*connect.Response[v1.ResolveReceiptActionResponse], error)
	GetModelReadiness(context.Context, *connect.Request[v1.GetModelReadinessRequest]) (*connect.Response[v1.GetModelReadinessResponse], error)
	GetClientSetup(context.Context, *connect.Request[v1.GetClientSetupRequest]) (*connect.Response[v1.GetClientSetupResponse], error)
	SubmitIssueReport(context.Context, *connect.Request[v1.SubmitIssueReportRequest]) (*connect.Response[v1.SubmitIssueReportResponse], error)
	CreateBusinessObject(context.Context, *connect.Request[v1.CreateBusinessObjectRequest]) (*connect.Response[v1.CreateBusinessObjectResponse], error)
	GetBusinessObject(context.Context, *connect.Request[v1.GetBusinessObjectRequest]) (*connect.Response[v1.GetBusinessObjectResponse], error)
	UpdateBusinessObject(context.Context, *connect.Request[v1.UpdateBusinessObjectRequest]) (*connect.Response[v1.UpdateBusinessObjectResponse], error)
	DeleteBusinessObject(context.Context, *connect.Request[v1.DeleteBusinessObjectRequest]) (*connect.Response[v1.DeleteBusinessObjectResponse], error)
}

// NewDeixicPublicServiceClient constructs a client for the deixicpublic.v1.DeixicPublicService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDeixicPublicServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DeixicPublicServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	deixicPublicServiceMethods := v1.File_deixicpublic_v1_sdk_proto.Services().ByName("DeixicPublicService").Methods()
	return &deixicPublicServiceClient{
		getThread: connect.NewClient[v1.GetThreadRequest, v1.GetThreadResponse](
			httpClient,
			baseURL+DeixicPublicServiceGetThreadProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("GetThread")),
			connect.WithClientOptions(opts...),
		),
		listThreads: connect.NewClient[v1.ListThreadsRequest, v1.ListThreadsResponse](
			httpClient,
			baseURL+DeixicPublicServiceListThreadsProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("ListThreads")),
			connect.WithClientOptions(opts...),
		),
		renameThread: connect.NewClient[v1.RenameThreadRequest, v1.RenameThreadResponse](
			httpClient,
			baseURL+DeixicPublicServiceRenameThreadProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("RenameThread")),
			connect.WithClientOptions(opts...),
		),
		archiveThread: connect.NewClient[v1.ArchiveThreadRequest, v1.ArchiveThreadResponse](
			httpClient,
			baseURL+DeixicPublicServiceArchiveThreadProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("ArchiveThread")),
			connect.WithClientOptions(opts...),
		),
		listEvents: connect.NewClient[v1.ListEventsRequest, v1.ListEventsResponse](
			httpClient,
			baseURL+DeixicPublicServiceListEventsProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		watchEvents: connect.NewClient[v1.WatchEventsRequest, v1.WatchEventsResponse](
			httpClient,
			baseURL+DeixicPublicServiceWatchEventsProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("WatchEvents")),
			connect.WithClientOptions(opts...),
		),
		submitTask: connect.NewClient[v1.SubmitTaskRequest, v1.SubmitTaskResponse](
			httpClient,
			baseURL+DeixicPublicServiceSubmitTaskProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("SubmitTask")),
			connect.WithClientOptions(opts...),
		),
		interruptTask: connect.NewClient[v1.InterruptTaskRequest, v1.InterruptTaskResponse](
			httpClient,
			baseURL+DeixicPublicServiceInterruptTaskProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("InterruptTask")),
			connect.WithClientOptions(opts...),
		),
		respondToRequest: connect.NewClient[v1.RespondToRequestRequest, v1.RespondToRequestResponse](
			httpClient,
			baseURL+DeixicPublicServiceRespondToRequestProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("RespondToRequest")),
			connect.WithClientOptions(opts...),
		),
		getReceipt: connect.NewClient[v1.GetReceiptRequest, v1.GetReceiptResponse](
			httpClient,
			baseURL+DeixicPublicServiceGetReceiptProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("GetReceipt")),
			connect.WithClientOptions(opts...),
		),
		resolveReceiptAction: connect.NewClient[v1.ResolveReceiptActionRequest, v1.ResolveReceiptActionResponse](
			httpClient,
			baseURL+DeixicPublicServiceResolveReceiptActionProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("ResolveReceiptAction")),
			connect.WithClientOptions(opts...),
		),
		getModelReadiness: connect.NewClient[v1.GetModelReadinessRequest, v1.GetModelReadinessResponse](
			httpClient,
			baseURL+DeixicPublicServiceGetModelReadinessProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("GetModelReadiness")),
			connect.WithClientOptions(opts...),
		),
		getClientSetup: connect.NewClient[v1.GetClientSetupRequest, v1.GetClientSetupResponse](
			httpClient,
			baseURL+DeixicPublicServiceGetClientSetupProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("GetClientSetup")),
			connect.WithClientOptions(opts...),
		),
		submitIssueReport: connect.NewClient[v1.SubmitIssueReportRequest, v1.SubmitIssueReportResponse](
			httpClient,
			baseURL+DeixicPublicServiceSubmitIssueReportProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("SubmitIssueReport")),
			connect.WithClientOptions(opts...),
		),
		createBusinessObject: connect.NewClient[v1.CreateBusinessObjectRequest, v1.CreateBusinessObjectResponse](
			httpClient,
			baseURL+DeixicPublicServiceCreateBusinessObjectProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("CreateBusinessObject")),
			connect.WithClientOptions(opts...),
		),
		getBusinessObject: connect.NewClient[v1.GetBusinessObjectRequest, v1.GetBusinessObjectResponse](
			httpClient,
			baseURL+DeixicPublicServiceGetBusinessObjectProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("GetBusinessObject")),
			connect.WithClientOptions(opts...),
		),
		updateBusinessObject: connect.NewClient[v1.UpdateBusinessObjectRequest, v1.UpdateBusinessObjectResponse](
			httpClient,
			baseURL+DeixicPublicServiceUpdateBusinessObjectProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("UpdateBusinessObject")),
			connect.WithClientOptions(opts...),
		),
		deleteBusinessObject: connect.NewClient[v1.DeleteBusinessObjectRequest, v1.DeleteBusinessObjectResponse](
			httpClient,
			baseURL+DeixicPublicServiceDeleteBusinessObjectProcedure,
			connect.WithSchema(deixicPublicServiceMethods.ByName("DeleteBusinessObject")),
			connect.WithClientOptions(opts...),
		),
	}
}

// deixicPublicServiceClient implements DeixicPublicServiceClient.
type deixicPublicServiceClient struct {
	getThread            *connect.Client[v1.GetThreadRequest, v1.GetThreadResponse]
	listThreads          *connect.Client[v1.ListThreadsRequest, v1.ListThreadsResponse]
	renameThread         *connect.Client[v1.RenameThreadRequest, v1.RenameThreadResponse]
	archiveThread        *connect.Client[v1.ArchiveThreadRequest, v1.ArchiveThreadResponse]
	listEvents           *connect.Client[v1.ListEventsRequest, v1.ListEventsResponse]
	watchEvents          *connect.Client[v1.WatchEventsRequest, v1.WatchEventsResponse]
	submitTask           *connect.Client[v1.SubmitTaskRequest, v1.SubmitTaskResponse]
	interruptTask        *connect.Client[v1.InterruptTaskRequest, v1.InterruptTaskResponse]
	respondToRequest     *connect.Client[v1.RespondToRequestRequest, v1.RespondToRequestResponse]
	getReceipt           *connect.Client[v1.GetReceiptRequest, v1.GetReceiptResponse]
	resolveReceiptAction *connect.Client[v1.ResolveReceiptActionRequest, v1.ResolveReceiptActionResponse]
	getModelReadiness    *connect.Client[v1.GetModelReadinessRequest, v1.GetModelReadinessResponse]
	getClientSetup       *connect.Client[v1.GetClientSetupRequest, v1.GetClientSetupResponse]
	submitIssueReport    *connect.Client[v1.SubmitIssueReportRequest, v1.SubmitIssueReportResponse]
	createBusinessObject *connect.Client[v1.CreateBusinessObjectRequest, v1.CreateBusinessObjectResponse]
	getBusinessObject    *connect.Client[v1.GetBusinessObjectRequest, v1.GetBusinessObjectResponse]
	updateBusinessObject *connect.Client[v1.UpdateBusinessObjectRequest, v1.UpdateBusinessObjectResponse]
	deleteBusinessObject *connect.Client[v1.DeleteBusinessObjectRequest, v1.DeleteBusinessObjectResponse]
}

// GetThread calls deixicpublic.v1.DeixicPublicService.GetThread.
func (c *deixicPublicServiceClient) GetThread(ctx context.Context, req *connect.Request[v1.GetThreadRequest]) (*connect.Response[v1.GetThreadResponse], error) {
	return c.getThread.CallUnary(ctx, req)
}

// ListThreads calls deixicpublic.v1.DeixicPublicService.ListThreads.
func (c *deixicPublicServiceClient) ListThreads(ctx context.Context, req *connect.Request[v1.ListThreadsRequest]) (*connect.Response[v1.ListThreadsResponse], error) {
	return c.listThreads.CallUnary(ctx, req)
}

// RenameThread calls deixicpublic.v1.DeixicPublicService.RenameThread.
func (c *deixicPublicServiceClient) RenameThread(ctx context.Context, req *connect.Request[v1.RenameThreadRequest]) (*connect.Response[v1.RenameThreadResponse], error) {
	return c.renameThread.CallUnary(ctx, req)
}

// ArchiveThread calls deixicpublic.v1.DeixicPublicService.ArchiveThread.
func (c *deixicPublicServiceClient) ArchiveThread(ctx context.Context, req *connect.Request[v1.ArchiveThreadRequest]) (*connect.Response[v1.ArchiveThreadResponse], error) {
	return c.archiveThread.CallUnary(ctx, req)
}

// ListEvents calls deixicpublic.v1.DeixicPublicService.ListEvents.
func (c *deixicPublicServiceClient) ListEvents(ctx context.Context, req *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// WatchEvents calls deixicpublic.v1.DeixicPublicService.WatchEvents.
func (c *deixicPublicServiceClient) WatchEvents(ctx context.Context, req *connect.Request[v1.WatchEventsRequest]) (*connect.ServerStreamForClient[v1.WatchEventsResponse], error) {
	return c.watchEvents.CallServerStream(ctx, req)
}

// SubmitTask calls deixicpublic.v1.DeixicPublicService.SubmitTask.
func (c *deixicPublicServiceClient) SubmitTask(ctx context.Context, req *connect.Request[v1.SubmitTaskRequest]) (*connect.Response[v1.SubmitTaskResponse], error) {
	return c.submitTask.CallUnary(ctx, req)
}

// InterruptTask calls deixicpublic.v1.DeixicPublicService.InterruptTask.
func (c *deixicPublicServiceClient) InterruptTask(ctx context.Context, req *connect.Request[v1.InterruptTaskRequest]) (*connect.Response[v1.InterruptTaskResponse], error) {
	return c.interruptTask.CallUnary(ctx, req)
}

// RespondToRequest calls deixicpublic.v1.DeixicPublicService.RespondToRequest.
func (c *deixicPublicServiceClient) RespondToRequest(ctx context.Context, req *connect.Request[v1.RespondToRequestRequest]) (*connect.Response[v1.RespondToRequestResponse], error) {
	return c.respondToRequest.CallUnary(ctx, req)
}

// GetReceipt calls deixicpublic.v1.DeixicPublicService.GetReceipt.
func (c *deixicPublicServiceClient) GetReceipt(ctx context.Context, req *connect.Request[v1.GetReceiptRequest]) (*connect.Response[v1.GetReceiptResponse], error) {
	return c.getReceipt.CallUnary(ctx, req)
}

// ResolveReceiptAction calls deixicpublic.v1.DeixicPublicService.ResolveReceiptAction.
func (c *deixicPublicServiceClient) ResolveReceiptAction(ctx context.Context, req *connect.Request[v1.ResolveReceiptActionRequest]) (*connect.Response[v1.ResolveReceiptActionResponse], error) {
	return c.resolveReceiptAction.CallUnary(ctx, req)
}

// GetModelReadiness calls deixicpublic.v1.DeixicPublicService.GetModelReadiness.
func (c *deixicPublicServiceClient) GetModelReadiness(ctx context.Context, req *connect.Request[v1.GetModelReadinessRequest]) (*connect.Response[v1.GetModelReadinessResponse], error) {
	return c.getModelReadiness.CallUnary(ctx, req)
}

// GetClientSetup calls deixicpublic.v1.DeixicPublicService.GetClientSetup.
func (c *deixicPublicServiceClient) GetClientSetup(ctx context.Context, req *connect.Request[v1.GetClientSetupRequest]) (*connect.Response[v1.GetClientSetupResponse], error) {
	return c.getClientSetup.CallUnary(ctx, req)
}

// SubmitIssueReport calls deixicpublic.v1.DeixicPublicService.SubmitIssueReport.
func (c *deixicPublicServiceClient) SubmitIssueReport(ctx context.Context, req *connect.Request[v1.SubmitIssueReportRequest]) (*connect.Response[v1.SubmitIssueReportResponse], error) {
	return c.submitIssueReport.CallUnary(ctx, req)
}

// CreateBusinessObject calls deixicpublic.v1.DeixicPublicService.CreateBusinessObject.
func (c *deixicPublicServiceClient) CreateBusinessObject(ctx context.Context, req *connect.Request[v1.CreateBusinessObjectRequest]) (*connect.Response[v1.CreateBusinessObjectResponse], error) {
	return c.createBusinessObject.CallUnary(ctx, req)
}

// GetBusinessObject calls deixicpublic.v1.DeixicPublicService.GetBusinessObject.
func (c *deixicPublicServiceClient) GetBusinessObject(ctx context.Context, req *connect.Request[v1.GetBusinessObjectRequest]) (*connect.Response[v1.GetBusinessObjectResponse], error) {
	return c.getBusinessObject.CallUnary(ctx, req)
}

// UpdateBusinessObject calls deixicpublic.v1.DeixicPublicService.UpdateBusinessObject.
func (c *deixicPublicServiceClient) UpdateBusinessObject(ctx context.Context, req *connect.Request[v1.UpdateBusinessObjectRequest]) (*connect.Response[v1.UpdateBusinessObjectResponse], error) {
	return c.updateBusinessObject.CallUnary(ctx, req)
}

// DeleteBusinessObject calls deixicpublic.v1.DeixicPublicService.DeleteBusinessObject.
func (c *deixicPublicServiceClient) DeleteBusinessObject(ctx context.Context, req *connect.Request[v1.DeleteBusinessObjectRequest]) (*connect.Response[v1.DeleteBusinessObjectResponse], error) {
	return c.deleteBusinessObject.CallUnary(ctx, req)
}

// DeixicPublicServiceHandler is an implementation of the deixicpublic.v1.DeixicPublicService
// service.
type DeixicPublicServiceHandler interface {
	GetThread(context.Context, *connect.Request[v1.GetThreadRequest]) (*connect.Response[v1.GetThreadResponse], error)
	ListThreads(context.Context, *connect.Request[v1.ListThreadsRequest]) (*connect.Response[v1.ListThreadsResponse], error)
	RenameThread(context.Context, *connect.Request[v1.RenameThreadRequest]) (*connect.Response[v1.RenameThreadResponse], error)
	ArchiveThread(context.Context, *connect.Request[v1.ArchiveThreadRequest]) (*connect.Response[v1.ArchiveThreadResponse], error)
	ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error)
	WatchEvents(context.Context, *connect.Request[v1.WatchEventsRequest], *connect.ServerStream[v1.WatchEventsResponse]) error
	SubmitTask(context.Context, *connect.Request[v1.SubmitTaskRequest]) (*connect.Response[v1.SubmitTaskResponse], error)
	InterruptTask(context.Context, *connect.Request[v1.InterruptTaskRequest]) (*connect.Response[v1.InterruptTaskResponse], error)
	RespondToRequest(context.Context, *connect.Request[v1.RespondToRequestRequest]) (*connect.Response[v1.RespondToRequestResponse], error)
	GetReceipt(context.Context, *connect.Request[v1.GetReceiptRequest]) (*connect.Response[v1.GetReceiptResponse], error)
	ResolveReceiptAction(context.Context, *connect.Request[v1.ResolveReceiptActionRequest]) (*connect.Response[v1.ResolveReceiptActionResponse], error)
	GetModelReadiness(context.Context, *connect.Request[v1.GetModelReadinessRequest]) (*connect.Response[v1.GetModelReadinessResponse], error)
	GetClientSetup(context.Context, *connect.Request[v1.GetClientSetupRequest]) (*connect.Response[v1.GetClientSetupResponse], error)
	SubmitIssueReport(context.Context, *connect.Request[v1.SubmitIssueReportRequest]) (*connect.Response[v1.SubmitIssueReportResponse], error)
	CreateBusinessObject(context.Context, *connect.Request[v1.CreateBusinessObjectRequest]) (*connect.Response[v1.CreateBusinessObjectResponse], error)
	GetBusinessObject(context.Context, *connect.Request[v1.GetBusinessObjectRequest]) (*connect.Response[v1.GetBusinessObjectResponse], error)
	UpdateBusinessObject(context.Context, *connect.Request[v1.UpdateBusinessObjectRequest]) (*connect.Response[v1.UpdateBusinessObjectResponse], error)
	DeleteBusinessObject(context.Context, *connect.Request[v1.DeleteBusinessObjectRequest]) (*connect.Response[v1.DeleteBusinessObjectResponse], error)
}

// NewDeixicPublicServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDeixicPublicServiceHandler(svc DeixicPublicServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	deixicPublicServiceMethods := v1.File_deixicpublic_v1_sdk_proto.Services().ByName("DeixicPublicService").Methods()
	deixicPublicServiceGetThreadHandler := connect.NewUnaryHandler(
		DeixicPublicServiceGetThreadProcedure,
		svc.GetThread,
		connect.WithSchema(deixicPublicServiceMethods.ByName("GetThread")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceListThreadsHandler := connect.NewUnaryHandler(
		DeixicPublicServiceListThreadsProcedure,
		svc.ListThreads,
		connect.WithSchema(deixicPublicServiceMethods.ByName("ListThreads")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceRenameThreadHandler := connect.NewUnaryHandler(
		DeixicPublicServiceRenameThreadProcedure,
		svc.RenameThread,
		connect.WithSchema(deixicPublicServiceMethods.ByName("RenameThread")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceArchiveThreadHandler := connect.NewUnaryHandler(
		DeixicPublicServiceArchiveThreadProcedure,
		svc.ArchiveThread,
		connect.WithSchema(deixicPublicServiceMethods.ByName("ArchiveThread")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceListEventsHandler := connect.NewUnaryHandler(
		DeixicPublicServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(deixicPublicServiceMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceWatchEventsHandler := connect.NewServerStreamHandler(
		DeixicPublicServiceWatchEventsProcedure,
		svc.WatchEvents,
		connect.WithSchema(deixicPublicServiceMethods.ByName("WatchEvents")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceSubmitTaskHandler := connect.NewUnaryHandler(
		DeixicPublicServiceSubmitTaskProcedure,
		svc.SubmitTask,
		connect.WithSchema(deixicPublicServiceMethods.ByName("SubmitTask")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceInterruptTaskHandler := connect.NewUnaryHandler(
		DeixicPublicServiceInterruptTaskProcedure,
		svc.InterruptTask,
		connect.WithSchema(deixicPublicServiceMethods.ByName("InterruptTask")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceRespondToRequestHandler := connect.NewUnaryHandler(
		DeixicPublicServiceRespondToRequestProcedure,
		svc.RespondToRequest,
		connect.WithSchema(deixicPublicServiceMethods.ByName("RespondToRequest")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceGetReceiptHandler := connect.NewUnaryHandler(
		DeixicPublicServiceGetReceiptProcedure,
		svc.GetReceipt,
		connect.WithSchema(deixicPublicServiceMethods.ByName("GetReceipt")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceResolveReceiptActionHandler := connect.NewUnaryHandler(
		DeixicPublicServiceResolveReceiptActionProcedure,
		svc.ResolveReceiptAction,
		connect.WithSchema(deixicPublicServiceMethods.ByName("ResolveReceiptAction")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceGetModelReadinessHandler := connect.NewUnaryHandler(
		DeixicPublicServiceGetModelReadinessProcedure,
		svc.GetModelReadiness,
		connect.WithSchema(deixicPublicServiceMethods.ByName("GetModelReadiness")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceGetClientSetupHandler := connect.NewUnaryHandler(
		DeixicPublicServiceGetClientSetupProcedure,
		svc.GetClientSetup,
		connect.WithSchema(deixicPublicServiceMethods.ByName("GetClientSetup")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceSubmitIssueReportHandler := connect.NewUnaryHandler(
		DeixicPublicServiceSubmitIssueReportProcedure,
		svc.SubmitIssueReport,
		connect.WithSchema(deixicPublicServiceMethods.ByName("SubmitIssueReport")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceCreateBusinessObjectHandler := connect.NewUnaryHandler(
		DeixicPublicServiceCreateBusinessObjectProcedure,
		svc.CreateBusinessObject,
		connect.WithSchema(deixicPublicServiceMethods.ByName("CreateBusinessObject")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceGetBusinessObjectHandler := connect.NewUnaryHandler(
		DeixicPublicServiceGetBusinessObjectProcedure,
		svc.GetBusinessObject,
		connect.WithSchema(deixicPublicServiceMethods.ByName("GetBusinessObject")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceUpdateBusinessObjectHandler := connect.NewUnaryHandler(
		DeixicPublicServiceUpdateBusinessObjectProcedure,
		svc.UpdateBusinessObject,
		connect.WithSchema(deixicPublicServiceMethods.ByName("UpdateBusinessObject")),
		connect.WithHandlerOptions(opts...),
	)
	deixicPublicServiceDeleteBusinessObjectHandler := connect.NewUnaryHandler(
		DeixicPublicServiceDeleteBusinessObjectProcedure,
		svc.DeleteBusinessObject,
		connect.WithSchema(deixicPublicServiceMethods.ByName("DeleteBusinessObject")),
		connect.WithHandlerOptions(opts...),
	)
	return "/deixicpublic.v1.DeixicPublicService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DeixicPublicServiceGetThreadProcedure:
			deixicPublicServiceGetThreadHandler.ServeHTTP(w, r)
		case DeixicPublicServiceListThreadsProcedure:
			deixicPublicServiceListThreadsHandler.ServeHTTP(w, r)
		case DeixicPublicServiceRenameThreadProcedure:
			deixicPublicServiceRenameThreadHandler.ServeHTTP(w, r)
		case DeixicPublicServiceArchiveThreadProcedure:
			deixicPublicServiceArchiveThreadHandler.ServeHTTP(w, r)
		case DeixicPublicServiceListEventsProcedure:
			deixicPublicServiceListEventsHandler.ServeHTTP(w, r)
		case DeixicPublicServiceWatchEventsProcedure:
			deixicPublicServiceWatchEventsHandler.ServeHTTP(w, r)
		case DeixicPublicServiceSubmitTaskProcedure:
			deixicPublicServiceSubmitTaskHandler.ServeHTTP(w, r)
		case DeixicPublicServiceInterruptTaskProcedure:
			deixicPublicServiceInterruptTaskHandler.ServeHTTP(w, r)
		case DeixicPublicServiceRespondToRequestProcedure:
			deixicPublicServiceRespondToRequestHandler.ServeHTTP(w, r)
		case DeixicPublicServiceGetReceiptProcedure:
			deixicPublicServiceGetReceiptHandler.ServeHTTP(w, r)
		case DeixicPublicServiceResolveReceiptActionProcedure:
			deixicPublicServiceResolveReceiptActionHandler.ServeHTTP(w, r)
		case DeixicPublicServiceGetModelReadinessProcedure:
			deixicPublicServiceGetModelReadinessHandler.ServeHTTP(w, r)
		case DeixicPublicServiceGetClientSetupProcedure:
			deixicPublicServiceGetClientSetupHandler.ServeHTTP(w, r)
		case DeixicPublicServiceSubmitIssueReportProcedure:
			deixicPublicServiceSubmitIssueReportHandler.ServeHTTP(w, r)
		case DeixicPublicServiceCreateBusinessObjectProcedure:
			deixicPublicServiceCreateBusinessObjectHandler.ServeHTTP(w, r)
		case DeixicPublicServiceGetBusinessObjectProcedure:
			deixicPublicServiceGetBusinessObjectHandler.ServeHTTP(w, r)
		case DeixicPublicServiceUpdateBusinessObjectProcedure:
			deixicPublicServiceUpdateBusinessObjectHandler.ServeHTTP(w, r)
		case DeixicPublicServiceDeleteBusinessObjectProcedure:
			deixicPublicServiceDeleteBusinessObjectHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDeixicPublicServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDeixicPublicServiceHandler struct{}

func (UnimplementedDeixicPublicServiceHandler) GetThread(context.Context, *connect.Request[v1.GetThreadRequest]) (*connect.Response[v1.GetThreadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.GetThread is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) ListThreads(context.Context, *connect.Request[v1.ListThreadsRequest]) (*connect.Response[v1.ListThreadsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.ListThreads is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) RenameThread(context.Context, *connect.Request[v1.RenameThreadRequest]) (*connect.Response[v1.RenameThreadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.RenameThread is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) ArchiveThread(context.Context, *connect.Request[v1.ArchiveThreadRequest]) (*connect.Response[v1.ArchiveThreadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.ArchiveThread is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.ListEvents is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) WatchEvents(context.Context, *connect.Request[v1.WatchEventsRequest], *connect.ServerStream[v1.WatchEventsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.WatchEvents is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) SubmitTask(context.Context, *connect.Request[v1.SubmitTaskRequest]) (*connect.Response[v1.SubmitTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.SubmitTask is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) InterruptTask(context.Context, *connect.Request[v1.InterruptTaskRequest]) (*connect.Response[v1.InterruptTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.InterruptTask is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) RespondToRequest(context.Context, *connect.Request[v1.RespondToRequestRequest]) (*connect.Response[v1.RespondToRequestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.RespondToRequest is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) GetReceipt(context.Context, *connect.Request[v1.GetReceiptRequest]) (*connect.Response[v1.GetReceiptResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.GetReceipt is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) ResolveReceiptAction(context.Context, *connect.Request[v1.ResolveReceiptActionRequest]) (*connect.Response[v1.ResolveReceiptActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.ResolveReceiptAction is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) GetModelReadiness(context.Context, *connect.Request[v1.GetModelReadinessRequest]) (*connect.Response[v1.GetModelReadinessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.GetModelReadiness is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) GetClientSetup(context.Context, *connect.Request[v1.GetClientSetupRequest]) (*connect.Response[v1.GetClientSetupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.GetClientSetup is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) SubmitIssueReport(context.Context, *connect.Request[v1.SubmitIssueReportRequest]) (*connect.Response[v1.SubmitIssueReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.SubmitIssueReport is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) CreateBusinessObject(context.Context, *connect.Request[v1.CreateBusinessObjectRequest]) (*connect.Response[v1.CreateBusinessObjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.CreateBusinessObject is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) GetBusinessObject(context.Context, *connect.Request[v1.GetBusinessObjectRequest]) (*connect.Response[v1.GetBusinessObjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.GetBusinessObject is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) UpdateBusinessObject(context.Context, *connect.Request[v1.UpdateBusinessObjectRequest]) (*connect.Response[v1.UpdateBusinessObjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.UpdateBusinessObject is not implemented"))
}

func (UnimplementedDeixicPublicServiceHandler) DeleteBusinessObject(context.Context, *connect.Request[v1.DeleteBusinessObjectRequest]) (*connect.Response[v1.DeleteBusinessObjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deixicpublic.v1.DeixicPublicService.DeleteBusinessObject is not implemented"))
}
